[project]
name = "scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "linkedin-jobs-scraper==5.0.2",
    "pydantic>=2.11.2",
    "pydantic-settings>=2.8.1",
]
